

<!DOCTYPE HTML>
<HTML LANG="AR">
<HEAD>
<TITLE>KADYSOFT</TITLE>
<META CHARSET="UTF-8">
<META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
<STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE></HEAD>
<BODY><CENTER>


<!-- CREATING RECIPE FROM KADYSOFT LTD.-->


<HTML LANG="AR">
 <HEAD> 
  <TITLE>KADYSOFT</TITLE> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
 </HEAD> 
 <BODY> 
  <CENTER> 
   <CENTER> 
    <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <CENTER> 
        <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
       </CENTER> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <CENTER> 
        <CENTER> 
         <CENTER> 
          <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
         </CENTER> 
        </CENTER> 
       </CENTER> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <META CHARSET="UTF-8"> 
  <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0"> 
  <STYLE>TD {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}
TABLE {
HEIGHT:5PX;
MAX-WIDTH:100%;
HEIGHT:100%;
WHITE-SPACE:NOWRAP;
}
TR {
HEIGHT:5PX;
MAX-WIDTH:100%;
WHITE-SPACE:NOWRAP;
}</STYLE> 
  <CENTER> 
   <CENTER> 
    <CENTER> 
     <CENTER> 
      <CENTER> 
       <CENTER> 
        <CENTER> 
         <CENTER> 
          <CENTER> 
           <!-- CREATING RECIPE FROM KADYSOFT LTD.--> 
           <TABLE ID="EXTABLE" STYLE="WIDTH: 1369PX;" BORDER="1" CELLSPACING="0"> 
            <TBODY> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>PRODUCTION RECIPE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>DATE:</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>10/08/2024</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>CUST :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>TOMMY</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>WASH NAME :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>AT.5167 WASHED BLUE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>PO NO :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>PO AMOUNT :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5123822</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>100</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>FABRIC NAME :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>MACHINE NO :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SPINING NO</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DRYER NO </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OPERATOR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>PCS :</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"><B>ACTION NO</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>ACTION NAME</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>TIME(MIN)</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>TEMP</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>LITER'S</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>AMT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>UNIT'S</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL NAME</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>CHEMICAL LOT NUMBER</B></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; BACKGROUND-COLOR: #FFFF00; TEXT-ALIGN: CENTER; HEIGHT: 18PX;"><B>SCRAPPING</B></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DESIZE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>50</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DESPIRES</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROSPERS TMS PLUS</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>LUBRICANT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROYA LUBE ACA</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>ENZYME STONE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>30</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>40</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>200</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>ENZYME</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ASUCELL WF</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>4</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GARDAL</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>NEW STONE</B></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;">STONE</TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>4</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GARDAL</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>OLD STONE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">STONE</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>800</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>GR</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DESPIRES</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROSPERS TMS PLUS</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>LASER AKTIVATOR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>300</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>1.5</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>LAC</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">LAVA CON LAC</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>4</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>LSB</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">LAVA CON LSB</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>عصاره R.B.M 30</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; BACKGROUND-COLOR: #FFFB00; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><B>عصارة 1 دقيقة</B></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; BACKGROUND-COLOR: #FFFB00; HEIGHT: 18PX; TEXT-ALIGN: CENTER;"><B>ثم يسلم لليزر</B></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>مجفف </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>LASER</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>CLEAN UP</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5 CONT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>40</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>1.5</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>PEROXIDE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">HYDROGEN PEROXIDE (H2O2)</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>100</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>COUSTIC</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">CAUSTIC SODA SODUIM HYDROXIDE</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>EXTRACT &AMP; DRYER</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; BACKGROUND-COLOR: #FFEA00; TEXT-ALIGN: CENTER; WIDTH: 146.844PX; HEIGHT: 18PX;"><STRONG>PP SPRAY</STRONG></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;"></TD> 
              <TD STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>PDT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>5</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>200</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>CRYSTAL</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROYACTIVEX KS</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>200</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>DESPIRES</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROSPERS TMS PLUS</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>RINSE </B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>20</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>TINT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>3</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>40</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>400</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><STRONG>1</STRONG></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>BLUE</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">TUBANTIN BLUE BRR H.C.</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>0.2</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>YELLOW</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">TUBANTIN YELLOW 2G</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>6</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SALT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">SALT-LOCAL</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SOFT</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>1</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; BACKGROUND-COLOR: #EAFF00; HEIGHT: 18PX;" ALIGN="CENTER"><B>ON SAME BATH</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>6</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>KG</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>SOFT CATIONIC</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ROSOFT ESQ 7820</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>TR22087150</B></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>200</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>GR</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"><B>ACID</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER">ACETIC ACID (CH3COOH)</TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="SELECTAREA" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER" BGCOLOR="#FFFF00"><B>EXTRACT &AMP; DRYER</B></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 190.609PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
             </TR> 
             <TR STYLE="HEIGHT: 18PX;"> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 120.672PX; HEIGHT: 18PX;" BGCOLOR="#FFFF00"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 170.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 99.625PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 146.844PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 82.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 86.5PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 109.641PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 185.203PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD CLASS="" STYLE="BORDER-STYLE: DOTTED; WIDTH: 134.766PX; HEIGHT: 18PX;" ALIGN="CENTER"></TD> 
              <TD STYLE="WIDTH: 190.609PX; HEIGHT: 18PX;"></TD> 
             </TR> 
             <TR> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><B>FIRST SHOT :</B> <U><B>137.8</B></U> <B>MINS.</B></TD> 
              <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><U><B>2.296666666666667</B></U> <B>HOURS.</B></TD> 
             </TR> 
             <TR> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%;"></TD> 
              <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><B>SECOND SHOT :</B> <U><B>36.9</B></U> <B>MINS.</B></TD> 
              <TD STYLE="WIDTH: 11.1111%; BACKGROUND-COLOR: #F6FF00; BORDER-COLOR: #FF0000; TEXT-ALIGN: CENTER;"><U><B>0.615</B></U> <B>HOURS.</B></TD> 
             </TR> 
            </TBODY> 
           </TABLE> 
          </CENTER> 
         </CENTER> 
        </CENTER> 
       </CENTER> 
      </CENTER> 
     </CENTER> 
    </CENTER> 
   </CENTER> 
  </CENTER> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE> 
  <STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>  
 </BODY>
</HTML>


</CENTER>
</BODY>
</HTML>
<B>MR_MUHAMMET SIGNATURE: </B><IMG SRC="FILE://Z:\MODELS\MR_MUHAMMET.PNG" WIDTH="300" HEIGHT="90" ALT="DEVELOPED BY KADYSOFT LTD (AHMED ELKADY)." STYLE="BORDER-COLOR:BLACK;BORDER-WIDTH:10PX;">


<STYLE>
BODY {
  BACKGROUND-IMAGE: URL("TOMMY_HILFIGER.BMP");
  BACKGROUND-POSITION: CENTER;
  HEIGHT: 170PX;
BACKGROUND-POSITION-X:550PX;  BACKGROUND-REPEAT: NO-REPEAT;
  BACKGROUND-SIZE: 120PX 90PX;
}
</STYLE>
